@startuml

skinparam nodesep 50
skinparam ranksep 80

title "Kryptograficky verifikovatelný auditní log: Kontejnery"

actor "Auditor" as Auditor
[Information System] as Producer <<Producer>>
'actor "Administrator" as Admin
'component "OpenBao (KMS)" as KMS

package "Tamper-Evident Audit Log System" {
    interface "Ingestion API" as IngestorAPI 
    interface "Query/Proof API" as ProofAPI
    [\tAudit Log Server\t] as LogServer <<Container>>
    
    database "Databáze" as AuditStore


    'interface "Audit API" as VerificationAPI
    [\tAudit Client\t] as Client <<Container>>

    database "Databáze" as RootStore
    
}

Producer .> IngestorAPI : Odesílá auditní záznamy\n<<gRPC API>>
IngestorAPI - LogServer
LogServer - ProofAPI

LogServer -down-> AuditStore : Ukládá auditní záznamy,\nkryptografické stopy\na checkpointy

'Auditor ..> VerificationAPI : Vyhledává auditní záznamy\na ověřuje důkazy integrity\n<<REST API>>
'Client - VerificationAPI
'VerificationAPI -- Client
Auditor ..> Client: Vyhledává auditní záznamy\na ověřuje důkazy integrity

ProofAPI <. Client: "Získává podepsané checkpointy \n a vyhledává auditní záznamy \n<<gRPC API>>"
Client -down-> RootStore : Ukládá \nlokální kopie \ncheckpointů

'LogServer --> KMS : Využívá klíče pro \n šifrování a digitální \npodepisování
'Client --> KMS : Ověřování \npodpepsaných\n checkpointů

@enduml
